Ubuntu bionic cleanup
cloudfoundry/bosh-linux-stemcell-builder pull request #204
Opened 2021-11-19 13:32 UTC by toabctl

2021-11-20 14:42 UTC, toabctl commented
I did a test build with `bundle exec rake --trace stemcell:build_os_image[ubuntu,bionic,/opt/bosh/tmp/ubuntu-bionic-pr-204.tgz]` and that passed.
Is there any CI involved for those kind of PRs ?

2021-11-22 10:17 UTC, toabctl commented
@rkoster maybe you could have a look given that you have a similar WIP branch for dropping `ixgbevf` custom installation?

2021-11-23 19:06 UTC, rkoster commented
For context:
- Original story from linked branch: https://www.pivotaltracker.com/n/projects/956238/stories/174635234
- Branch was never merged and instead the following commit was made against the bionic branch: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/fc0a38a419c3a57a664a8b6459330387bc6240c1

2021-11-23 19:11 UTC, rkoster requested changes
It was no clear to me why dracut should be removed. Also from motivation for removing this package was not given in the PR description.

2021-11-23 19:11 UTC, rkoster commented on stemcell_builder/stages/base_apt/apply.sh
> -pkg_mgr install dracut
Why is dracut removed?

2021-11-24 12:42 UTC, toabctl commented on stemcell_builder/stages/base_apt/apply.sh
> -pkg_mgr install dracut
@rkoster I updated the commit message. Quoting here the 2 reasons:
```
- initramfs tools is the default way on Ubuntu for creating initial
  ramdisk. That means that it's in the "main" component which is
  supported by the Ubuntu security team[1]. dracut is in universe
  which is not supported by the Ubuntu security team.
- the Ubuntu FIPS[0] packages can depend on initramfs tools. So
  installing those FIPS packages does not work with dracut.
```

2021-11-24 12:44 UTC, toabctl commented on stemcell_builder/stages/base_apt/apply.sh
> -pkg_mgr install dracut
For context - I plan to propose more patches to be able to build a Ubuntu Bionic FIPS stemcell. I have a [POC](https://github.com/toabctl/bosh-linux-stemcell-builder/commit/7b9edb1b7b4478f95488102cd0e02754412c186a) for that and plan to introduce those changes with propper small commits. There are still some TODOs but the build & the stemcell in general works already.

2021-11-25 09:40 UTC, ramonskie commented on stemcell_builder/stages/base_apt/apply.sh
> -pkg_mgr install dracut
i think we should keep FIPS enabled stemcells and the opensource ones separate.
we can use one repo but then we can use an extra stage.
where it will configure everything FIPS releated

2021-11-25 12:20 UTC, rkoster commented on stemcell_builder/stages/base_apt/apply.sh
> -pkg_mgr install dracut
I agree with @ramonskie, since FIPS support requires a `Ubuntu Advantage` subscription we can not make the OSS stemcells FIPS complaint by default. So these stemcells would need to be built manually, making this easier by having a flag or target in the stemcell builder would definitely be an option here.

With regards the removal of `dracut`, it is unclear to me at this point if other releases might depend on this. So I'm considering this a breaking change for now. I don't see a lot of value in making this change in bionic but it would be a great time to submit this change for jammy now (since that's still in alpha, the branch can be found [here](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-jammy/master)).

The rest of the PR looks good to me, so if you could remove the changes related to switching from dracut to initframfs, this PR can be merged.

PS: Also found that at some point in time we switched from initframfs to dracut: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/eb7c3c441d1c05476c2fd7b6a2eb1c69eeae8ad2 unfortunately there are no details provided on their motivation.

2021-11-26 09:05 UTC, toabctl commented on stemcell_builder/stages/base_apt/apply.sh
> -pkg_mgr install dracut
Yes, the idea is to have most of the FIPS related code in an exta stage (see https://github.com/toabctl/bosh-linux-stemcell-builder/tree/7b9edb1b7b4478f95488102cd0e02754412c186a/stemcell_builder/stages/base_apt_fips ).
But having **all** FIPS related code in a single stage is difficult. In some stages, there would need to be an `if THIS_IS_FIPS; then do X; else do Y;`
Would that kind of `if/else` be ok in other stages?
Eg. this `dracut` installation is one of theses stages that would not work for FIPS (because this would remove all the FIPS packages again)
Another option would be to have the `if/else` in the stage_collection and have (where needed) `default` and `fips` stages.

2021-11-26 09:08 UTC, toabctl commented on stemcell_builder/stages/base_apt/apply.sh
> -pkg_mgr install dracut
@rkoster split out the change for dropping `ixgbevf` manual installation into https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/206 .

2021-11-26 09:11 UTC, toabctl commented on stemcell_builder/stages/base_apt/apply.sh
> -pkg_mgr install dracut
I'll PR the dracut removal for Jammy when #207 got merged.

2021-11-30 14:14 UTC, ramonskie approved these changes

2021-12-01 16:15 UTC, rkoster commented
@toabctl https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/207 has been merged

2021-12-01 16:19 UTC, rkoster approved these changes

2021-12-01 16:20 UTC, rkoster commented
Thanks! @toabctl

2021-12-01 16:20 UTC, merged

2021-12-02 08:35 UTC, toabctl commented
@rkoster @ramonskie I don't want to complain, but I thought you **don't** want to merge **this** PR? Now dracut support got removed for bionic.
Don't get me wrong - I'm happy that it got removed. Just want to make sure that this is really what you wanted to do?!

p.s. https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/208 is the dracut removal for `ubuntu-jammy/master` .

2021-12-02 08:36 UTC, toabctl commented on stemcell_builder/stages/base_apt/apply.sh
> -pkg_mgr install dracut
dracut removal for Jammy is now https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/208

2021-12-02 11:29 UTC, rkoster commented
@toabctl yeah we talked it over a bit more and decided it's okey for bionic.