RHEL 8.5 support
cloudfoundry/bosh-linux-stemcell-builder pull request #225
Opened 2022-04-15 23:07 UTC by Justin-W

This PR re-introduces support for building RHEL and CentOS stemcells.

It relies on corresponding bosh-agent changes in https://github.com/cloudfoundry/bosh-agent/pull/278.

2022-04-18 17:18 UTC, Justin-W commented
All CLA issues should be resolved now. Re-running the check, as described [here](https://docs.linuxfoundation.org/v2/easycla/getting-started/easycla-troubleshooting#github-pull-request-is-not-passing):

/easycla

2022-04-19 12:41 UTC, ramonskie commented
just wanted to let you know that we are not using the ci configured in this repo but from https://github.com/cloudfoundry/bosh-stemcells-ci.git

2022-04-19 14:32 UTC, ramonskie commented
i don't think this was meant to be compared to jammy correct?
as it seems that this pr is branched of bionic instead.

2022-04-19 17:46 UTC, Justin-W commented
> i don't think this was meant to be compared to jammy correct? as it seems that this pr is branched of bionic instead.

No, this PR was branched directly off of the [ubuntu-jammy/master](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-jammy/master) branch.

@rkoster told me that [ubuntu-jammy/master](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/ubuntu-jammy/master) will soon become the default branch, and he and I agreed that this change would best be merged into that branch. So that's where I branched from and am merging to.

2022-04-19 17:51 UTC, Justin-W commented
> just wanted to let you know that we are not using the ci configured in this repo but from https://github.com/cloudfoundry/bosh-stemcells-ci.git

Thanks. We are currently testing the new RHEL functionality via our own CI system. Adding RHEL into the https://github.com/cloudfoundry/bosh-stemcells-ci code could be a potentially useful enhancement, but that decision hasn't been made yet.

2022-05-06 07:40 UTC, ramonskie commented on ci/docker/run
> +
this breaks it for jammy.
i would suggest if not centos than set this option.
if it is a really issue centos

2022-05-06 07:40 UTC, ramonskie commented on stemcell_builder/stages/base_file_permission/apply.sh
> +
these will be included in building ubuntu stemcells.
and there fore a build will fail
my suggestion would be to put redhat specefics in different stage files
so we have better oversight

2022-06-02 13:35 UTC, rkoster requested changes
Great work on this huge PR. There are still some things that need to be resolved / cleaned up but again great work.

2022-06-02 13:35 UTC, rkoster commented on bosh-stemcell/lib/bosh/stemcell/stage_collection.rb
> +        :system_users,
Why was this stage added?

2022-06-02 13:35 UTC, rkoster commented on bosh-stemcell/spec/assets/run_in_chroot_exit_with_error.sh
> +  "
Why has this file been added?

2022-06-02 13:35 UTC, rkoster commented on bosh-stemcell/spec/assets/run_in_chroot_pwd.sh
> +run_in_chroot $chroot 'pwd'
Why has this file been added?

2022-06-02 13:35 UTC, rkoster commented on bosh-stemcell/spec/bosh/stemcell/stage_collection_spec.rb
> +              :system_users,
Why was this stage added?

2022-06-02 13:35 UTC, rkoster commented on bosh-stemcell/spec/bosh/stemcell/stemcell_builder_spec.rb
> +  let(:operating_system) { Bosh::Stemcell::OperatingSystem.for('centos') }
why is ubuntu not tested?

2022-06-02 13:35 UTC, rkoster commented on bosh-stemcell/spec/bosh/stemcell/stemcell_packager_spec.rb
> +  let(:operating_system) { Bosh::Stemcell::OperatingSystem.for('centos','7') }
why is ubuntu no longer tested?

2022-06-02 13:35 UTC, rkoster commented on bosh-stemcell/spec/stemcells/go_agent_spec.rb
> +      its(:content) { should include('"PartitionerType": "parted"') }
Why was this added?

2022-06-02 13:35 UTC, rkoster commented on ci/centos-7/configure-aggregated-pipeline.sh
> +  -l <(lpass show --notes "stemcell-reminder-bot")
This file should be removed since nobody is using this pipeline

2022-06-02 13:35 UTC, rkoster commented on ci/centos-7/pipeline-base.yml
> +    interval: 192h
This file is not used please remove

2022-06-02 13:35 UTC, rkoster commented on ci/centos-7/pipeline-branch-ops.yml
> +        tag: release-metadata/tag
This file is not used please remove

2022-06-02 13:35 UTC, rkoster commented on ci/centos-7/pipeline-base-ops.yml
> +    type: s3
This file is not used please remove

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/base_file_permission/apply.sh
> +
Shouldn't these changes be wrapped in an os specific conditional?

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/base_warden/apply.sh
> +if grep -q -i ubuntu $chroot/etc/lsb-release
this should use the helper function

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/bosh_go_agent/apply.sh
> +# TODO: figure out why this is a existing symlink now in jammy by default (see commits a41d51c0, 30db35c2)
Has this been figured out?

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/bosh_ntp/config.sh
> +persist stemcell_operating_system_version
This file does not seem to do anything

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/bosh_sysctl/apply.sh
> +   [ "${stemcell_operating_system}" == "rhel" ]; then
Since we don't care about centos and this gets installed on both ubuntu and rhel, this condition should be removed.

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/bosh_users/apply.sh
> +if [ -f $chroot/etc/debian_version ] # Ubuntu
why no check using `stemcell_operating_system`

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/dev_tools_config/apply.sh
> +if [ "${os_type}" == "ubuntu" ] || [ "${os_type}" == "centos" ] || [ "${os_type}" == "rhel" ] ; then
conditional could be removed.

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/dev_tools_config/assets/generate_dev_tools_file_list_ubuntu.sh
> +
why was this added?

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/system_google_packages/apply.sh
> +  echo "" > "$chroot/etc/growroot-disabled"
this line would also be needed for ubuntu

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/system_open_vm_tools/apply.sh
> +rhsm_register
This will probably fail on ubuntu and should be wrapped in a conditional.

2022-06-02 13:35 UTC, rkoster commented on stemcell_builder/stages/system_parameters/apply.sh
> +# the bosh-agent submodule. See
Is this still needed?

2022-06-30 14:05 UTC, closed without merging