NATS access helper aids troubleshooting
cloudfoundry/bosh-linux-stemcell-builder pull request #228
Opened 2022-04-26 22:36 UTC by cunnie

Newest stemcells prevent processes from accessing NATS (port 4222) on the BOSH Director because security; however, this can hamper troubleshooting.

This commit adds a helper script to enable an operator to access the NATS port on the director; it accomplishes this by adding the PID to the cgroup which is allowed to communicate with the Director's NATS server.

2022-04-27 08:12 UTC, ramonskie approved these changes

2022-04-27 08:19 UTC, ramonskie requested changes
Reject

2022-05-05 14:44 UTC, rkoster commented
@nouseforaname could you update this PR with your concerns?

2022-05-16 17:41 UTC, ragaskar commented
We think the documentation on bosh.io regarding getting access to NATS is simpler to use/maintain over having this script, so we're going to simply close out this PR.

2022-05-16 17:41 UTC, closed without merging