Moving phc conf to chrony config
cloudfoundry/bosh-linux-stemcell-builder pull request #288
Opened 2023-04-17 15:41 UTC by lnguyen

Note that this PR is merely a file change—instead of being placed in the `sources.d/ ` subdirectory, the directive to use the reference clock is placed in the `conf.d/` subdirectory, for the directive to use the reference clock is **not** a source definition; rather, it's a configuration definition.

If placed in `source.d/`, the directive has no effect.
[#184816605] Fix chrony azure phc config and update Ops Manager documentation

2023-04-17 17:05 UTC, cunnie requested changes
This is great! Thanks.

Could you please re-write the commit message to include something along the lines of the following:

> Note that this PR is merely a file change—instead of being placed in the `sources.d/` subdirectory, the directive to use the reference clock is placed in the `conf.d/` subdirectory. The directive doesn't work if it's placed in `sources.d` because it's not a source directive, it's a configuration directive.

2023-04-17 17:17 UTC, lnguyen commented
Updated @cunnie

2023-04-17 22:19 UTC, jpalermo approved these changes
👍

2023-04-17 23:15 UTC, cunnie commented
@lnguyen Oops, I meant could you please include that text in the _git_ commit message, not the _PR_ commit message. I always look at _git_, rarely at PRs. Thanks.

2023-04-18 11:31 UTC, lnguyen commented
ugh... i cant fix this commit message cause its on protected branch...

2023-04-18 12:08 UTC, ramonskie commented
ahh yes its protected due to `ubuntu-jammy\*` branch rule
so we either accept how it is for now.
or you need to rename the branch

2023-04-18 13:29 UTC, lnguyen commented
Moving PR to https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/289

2023-04-18 13:29 UTC, closed without merging