Create and bundle sbom.spdx.json as part of stemcell creation
cloudfoundry/bosh-linux-stemcell-builder pull request #336
Opened 2024-03-22 15:11 UTC by rthill91

- Install syft in image via Dockerfile
- Add new sbom_create stage to generate sbom.spdx.json as part of stemcell creation
- Bundle sbom.spdx.json into resulting stemcell tgz

2024-03-25 19:08 UTC, rkoster requested changes
PR looks great! Not sure if we want to do some filtering to reduce false positives (at some point the google agent tools had a dev dependency which would be picked up by syft). But those could also be done at a later point in time, once people start consuming the sbom and provide feedback.

2024-03-25 19:08 UTC, rkoster commented on ci/docker/os-image-stemcell-builder-jammy/Dockerfile
> +RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
Please use an immutable URL and digest verification.

2024-03-25 19:22 UTC, ragaskar commented
I agree w/ @rkoster that there should be some provision for checking the provenance of the install script/installed libraries. 

I can also share that in our experience, we've seen issues with tracking latest `syft` in that new features are added very quickly and occasionally these new features have undesirable impacts (e.g., we've seen new cataloguers suddenly introduce records for dozens of libraries that -- in our case -- were all false positives). It might be nice to have a way to easily pin syft when necessary. It's possible there is some implementation overlap with provenance for version pinning, so perhaps it makes sense to take that on now.

2024-03-25 19:25 UTC, ragaskar submitted a review, later dismissed
See my comment above, I see @rkoster is already asking for some validation strategy with the syft install, which I agree with. 

I don't think the version-pinning provision I mentioned is required so I'll give this a thumbs up, but it's a definite nice-to-have that may intersect with the provenance piece.

2024-03-25 19:27 UTC, ragaskar commented
also, thanks for this contribution, cool stuff!

2024-03-28 15:30 UTC, rkoster commented on ci/docker/os-image-stemcell-builder-jammy/Dockerfile
> +    rm install.sh syft.checksum
I would prefer a simple one-liner like: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/4481987e71b816ae0bf7f20119adc3aa7f610cf4/ci/docker/os-image-stemcell-builder-jammy/Dockerfile#L113-L116 over downloading and executing an external install script.

2024-03-28 15:44 UTC, beyhan commented
What is the estimated size of the generated SBOM? Have you also tried the other formats supported like the cycloneDX and the syft own format?

2024-03-28 17:40 UTC, rthill91 commented
> What is the estimated size of the generated SBOM? Have you also tried the other formats supported like the cycloneDX and the syft own format?

~34M in my jammy fips test build from today.

As for other formats, minimal consideration was given beyond the desire for something generic and machine readable. That put syft format out. Beyond that, internally spdx is the chosen format.

2024-04-11 15:04 UTC, rkoster submitted a review, later dismissed

2024-04-14 21:37 UTC, VinodAnandan commented
@rthill91 Could you please consider adding support for CycloneDX format as well?

2024-04-15 07:39 UTC, rkoster commented
Our internal tooling uses CycloneDX, so supporting both formats would be a plus for us.
The `cyclonedx-json` output format [seems to be supported by syft](https://github.com/anchore/syft?tab=readme-ov-file#output-formats).

2024-04-15 12:41 UTC, rthill91 commented
> Our internal tooling uses CycloneDX, so supporting both formats would be a plus for us. The `cyclonedx-json` output format [seems to be supported by syft](https://github.com/anchore/syft?tab=readme-ov-file#output-formats). But this is not a blocker for me and could be done by someone else in a later PR. I just want to make sure the discussion about supporting multiple formats is captured here.

syft definitely supports cyclonedx. The only complexity (off the top of my head) to adding support is that it makes it turns sbom generation into a configurable option rather than a static thing and it'll make the expected files in the output tgz configurable. I could just change the sbom to `sbom.json` to avoid that last bit, but I like the clarity of specifying that it's spdx, particularly if there's support for other formats included.

I'm don't mind working this, but it'll likely have to wait a few weeks (Noble release is going to keep me busy) and I'd rather it be a separate PR.

2024-04-15 17:49 UTC, rkoster commented
I would not make it an optional build flag, but instead just include both sboms, similar to what buildpacks are doing: https://github.com/buildpacks/rfcs/blob/main/text/0095-sbom.md#what-it-is

So we would end up with something like:
```ruby
expected = ['stemcell.MF', 'packages.txt', 'dev_tools_file_list.txt', 'image', 'sbom.spdx.json', 'sbom.cdx.json']
```

2024-04-16 13:11 UTC, rthill91 commented
> I would not make it an optional build flag, but instead just include both sboms, similar to what buildpacks are doing: https://github.com/buildpacks/rfcs/blob/main/text/0095-sbom.md#what-it-is
> 
> So we would end up with something like:
> 
> ```ruby
> expected = ['stemcell.MF', 'packages.txt', 'dev_tools_file_list.txt', 'image', 'sbom.spdx.json', 'sbom.cdx.json']
> ```

including both makes this a trivial change. I have it staged locally but I'm seeing some test failures (going through the non-iaas-kernel tests rather than aws specific kernel). I'll have to look at this a bit later

2024-04-17 18:31 UTC, rthill91 commented
updated to generate cyclonedx and spdx sboms

2024-04-17 19:41 UTC, rkoster requested changes

2024-04-17 19:41 UTC, rkoster commented on bosh-stemcell/lib/bosh/stemcell/stemcell_packager.rb
> +        expected = ['stemcell.MF', 'packages.txt', 'dev_tools_file_list.txt', 'image', 'sbom.spdx.json', 'sbom.cyclonedx.json']
According to: https://cyclonedx.org/specification/overview/#recognized-file-patterns
the filename should match `*.cdx.json`

2024-04-19 14:56 UTC, rkoster approved these changes

2024-04-22 17:56 UTC, rthill91 commented
updated title/description to reflect the addition of cdx sbom

2024-04-22 18:46 UTC, ragaskar approved these changes
thank you, looks great.

2024-04-23 12:37 UTC, rkoster commented
Thanks! @rthill91

2024-04-23 12:37 UTC, merged