stemcell-acceptance-tests use ginkgo version from go.mod
cloudfoundry/bosh-linux-stemcell-builder pull request #370
Opened 2024-07-24 22:43 UTC by aramprice

... instead of installing the hard-coded v2.2.0

2024-07-25 00:34 UTC, selzoc requested changes

2024-07-25 00:34 UTC, selzoc commented on src/github.com/cloudfoundry/stemcell-acceptance-tests/bin/test-smoke
> +$bin/go github.com/onsi/ginkgo/v2/ginkgo --skip-package ./vendor -r "$@"
should this not be `$bin/go run...` ?

2024-07-25 16:24 UTC, aramprice commented on src/github.com/cloudfoundry/stemcell-acceptance-tests/bin/test-smoke
> +$bin/go github.com/onsi/ginkgo/v2/ginkgo --skip-package ./vendor -r "$@"
doh, yes

2024-07-25 16:43 UTC, selzoc approved these changes

2024-07-26 12:40 UTC, lnguyen approved these changes

2024-07-26 16:41 UTC, merged