add DiskIDTransform Rules
cloudfoundry/bosh-linux-stemcell-builder pull request #403
Opened 2024-12-20 12:21 UTC by ramonskie

this will add the diskid transform rules needed for https://github.com/cloudfoundry/bosh-agent/pull/343

2024-12-20 19:33 UTC, jpalermo submitted a review, later dismissed

2024-12-27 07:10 UTC, fmoehler approved these changes

2025-01-09 16:01 UTC, rkoster requested changes
As discussed during Working group call, could you add a bit of documentation so that further people know what the paths where that we want to match against.

2025-01-09 22:13 UTC, jpalermo commented on stemcell_builder/stages/bosh_aws_agent_settings/assets/agent.json
> +      "DiskIDTransformPattern": "^(vol-(.+))$",
Are two capture groups needed here? Doesn't seem like the outer capture group is used.

2025-01-10 09:29 UTC, ramonskie commented on stemcell_builder/stages/bosh_aws_agent_settings/assets/agent.json
> +      "DiskIDTransformPattern": "^(vol-(.+))$",
that is correct. we can change this capture group

2025-01-10 09:29 UTC, fmoehler commented on stemcell_builder/stages/bosh_alicloud_agent_settings/assets/agent.md
> +do not that if this fails. it will always fallback to other means of mounting the disk
two typos. think it should be:
Do not**e** that if this fails it will always fallback to other means of mounting the disk. Same for the other docs.

2025-01-13 08:59 UTC, benjaminguttmann-avtq commented on stemcell_builder/stages/bosh_openstack_agent_settings/assets/agent.md
> +as you can see in the related information part.
```suggestion
The problem that we have is that the diskID provided by the IAAS does not correspond with the diskID on the vm as you can see in the related information part.
```

Not sure if that line break is needed and intended

2025-01-13 09:05 UTC, benjaminguttmann-avtq commented on stemcell_builder/stages/bosh_openstack_agent_settings/assets/agent.md
> +Therefore we are trying to mitigate this issue by using diskIdTransformation as you can see in the example below
```suggestion
Therefore, we are trying to mitigate this issue by using diskIdTransformation as you can see in the example below
```

I think therefore always comes with a comma

2025-01-13 09:06 UTC, benjaminguttmann-avtq commented on stemcell_builder/stages/bosh_google_agent_settings/assets/agent.md
> +as you can see in the related information part.
```suggestion
The problem that we have is that the diskID provided by the IAAS does not correspond with the diskID on the vm as you can see in the related information part.
```
see below

2025-01-13 09:07 UTC, benjaminguttmann-avtq commented on stemcell_builder/stages/bosh_google_agent_settings/assets/agent.md
> +Therefore we are trying to mitigate this issue by using diskIdTransformation as you can see in the example below
```suggestion
Therefore, we are trying to mitigate this issue by using diskIdTransformation as you can see in the example below
```

2025-01-13 09:07 UTC, benjaminguttmann-avtq commented on stemcell_builder/stages/bosh_aws_agent_settings/assets/agent.md
> +as you can see in the related information part.
```suggestion
The problem that we have is that the diskID provided by the IAAS does not correspond with the diskID on the vm as you can see in the related information part.
```

2025-01-13 09:07 UTC, benjaminguttmann-avtq commented on stemcell_builder/stages/bosh_aws_agent_settings/assets/agent.md
> +Therefore we are trying to mitigate this issue by using diskIdTransformation as you can see in the example below
```suggestion
Therefore, we are trying to mitigate this issue by using diskIdTransformation as you can see in the example below
```

2025-01-13 09:07 UTC, benjaminguttmann-avtq commented on stemcell_builder/stages/bosh_alicloud_agent_settings/assets/agent.md
> +as you can see in the related information part.
```suggestion
The problem that we have is that the diskID provided by the IAAS does not correspond with the diskID on the vm as you can see in the related information part.
```

2025-01-13 09:07 UTC, benjaminguttmann-avtq commented on stemcell_builder/stages/bosh_alicloud_agent_settings/assets/agent.md
> +Therefore we are trying to mitigate this issue by using diskIdTransformation as you can see in the example below
```suggestion
Therefore, we are trying to mitigate this issue by using diskIdTransformation as you can see in the example below
```

2025-01-16 15:54 UTC, beyhan approved these changes

2025-01-16 15:56 UTC, merged